server:
  port: 8888

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.53.217.86:3306/lzx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Lzx1922026241@

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.lzx.mybatis.generator.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl